/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.projetoprimefei.View;

import com.mycompany.projetoprimefei.controller.Controller;
import javax.swing.JButton;

/**
 *
 * @author luk
 */
public class TelaInicial extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.
            Logger.getLogger(TelaInicial.class.getName());

    /**
     * Creates new form TelaInicial
     */
    public TelaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrimeFEI = new javax.swing.JLabel();
        BtnIrCadastrar = new javax.swing.JButton();
        BtnIrLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PrimeFEI.setFont(new java.awt.Font("Papyrus", 2, 36)); // NOI18N
        PrimeFEI.setText("Prime FEI");

        BtnIrCadastrar.setText("Cadastrar");
        BtnIrCadastrar.addActionListener(this::BtnIrCadastrarActionPerformed);

        BtnIrLogin.setText("Login");
        BtnIrLogin.addActionListener(this::BtnIrLoginActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(BtnIrCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BtnIrLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(PrimeFEI, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(108, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(PrimeFEI)
                .addGap(26, 26, 26)
                .addComponent(BtnIrCadastrar)
                .addGap(18, 18, 18)
                .addComponent(BtnIrLogin)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIrCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIrCadastrarActionPerformed
        // TODO add your handling code here:
        controller.exibirCadastro();
    }//GEN-LAST:event_BtnIrCadastrarActionPerformed

    private void BtnIrLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIrLoginActionPerformed
        // TODO add your handling code here:
         controller.exibirLogin();
    }//GEN-LAST:event_BtnIrLoginActionPerformed
      
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaInicial().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIrCadastrar;
    private javax.swing.JButton BtnIrLogin;
    private javax.swing.JLabel PrimeFEI;
    // End of variables declaration//GEN-END:variables
    private Controller controller;
    
    public void setController(Controller controller){
        this.controller = controller;
    }

    public JButton getBtnIrCadastrar() {
        return BtnIrCadastrar;
    }

    public JButton getBtnIrLogin() {
        return BtnIrLogin;
    }

   

}
